stages:
  - build

variables:
  PLATFORM:
    value: "aarch64-rpi4-linux-gnu"
    description: "Target platform to build for. See docker/build-wip.sh for available platforms."
  REGISTRY: registry.rosetta.ericssondevops.com/ewasjon/supl-3gpp-lpp-client

build:
  stage: build
  image: docker:latest
  tags:
    - lsp-runner
  before_script:
    - apk add --no-cache python3 git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - BRANCH=$(git rev-parse --abbrev-ref HEAD)
    - python3 docker/build-images.py
        --platform "$PLATFORM"
        --build-mode debug
        --registry "$REGISTRY"
        --tag "$BRANCH"
        --no-provenance
        --force
    - TAG="${BRANCH}-debug"
    - docker push "$REGISTRY/tools/$PLATFORM:$TAG"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH =~ /^2026-summer-/
      when: manual
