/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/martin/repos/LPP-Client/asn/LPP.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_Abort_H_
#define	_Abort_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Abort-r9-IEs.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Abort__criticalExtensions_PR {
	Abort__criticalExtensions_PR_NOTHING,	/* No components present */
	Abort__criticalExtensions_PR_c1,
	Abort__criticalExtensions_PR_criticalExtensionsFuture
} Abort__criticalExtensions_PR;
typedef enum Abort__criticalExtensions__c1_PR {
	Abort__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	Abort__criticalExtensions__c1_PR_abort_r9,
	Abort__criticalExtensions__c1_PR_spare3,
	Abort__criticalExtensions__c1_PR_spare2,
	Abort__criticalExtensions__c1_PR_spare1
} Abort__criticalExtensions__c1_PR;

/* Abort */
typedef struct Abort {
	struct Abort__criticalExtensions {
		Abort__criticalExtensions_PR present;
		union Abort__criticalExtensions_u {
			struct Abort__criticalExtensions__c1 {
				Abort__criticalExtensions__c1_PR present;
				union Abort__criticalExtensions__c1_u {
					Abort_r9_IEs_t	 abort_r9;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} c1;
			struct Abort__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Abort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort;
extern asn_SEQUENCE_specifics_t asn_SPC_Abort_specs_1;
extern asn_TYPE_member_t asn_MBR_Abort_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Abort_H_ */
#include <asn_internal.h>
