/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/martin/repos/LPP-Client/asn/LPP.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_AlmanacMidiAlmanacSet_H_
#define	_AlmanacMidiAlmanacSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SV-ID.h"
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlmanacMidiAlmanacSet */
typedef struct AlmanacMidiAlmanacSet {
	SV_ID_t	 svID;
	long	 midiAlmE;
	long	 midiAlmDeltaI;
	long	 midiAlmOmegaDot;
	long	 midiAlmSqrtA;
	long	 midiAlmOmega0;
	long	 midiAlmOmega;
	long	 midiAlmMo;
	long	 midiAlmaf0;
	long	 midiAlmaf1;
	BOOLEAN_t	 midiAlmL1Health;
	BOOLEAN_t	 midiAlmL2Health;
	BOOLEAN_t	 midiAlmL5Health;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlmanacMidiAlmanacSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlmanacMidiAlmanacSet;
extern asn_SEQUENCE_specifics_t asn_SPC_AlmanacMidiAlmanacSet_specs_1;
extern asn_TYPE_member_t asn_MBR_AlmanacMidiAlmanacSet_1[13];

#ifdef __cplusplus
}
#endif

#endif	/* _AlmanacMidiAlmanacSet_H_ */
#include <asn_internal.h>
