/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/martin/repos/LPP-Client/asn/LPP.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_EPDU_Sequence_H_
#define	_EPDU_Sequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EPDU;

/* EPDU-Sequence */
typedef struct EPDU_Sequence {
	A_SEQUENCE_OF(struct EPDU) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPDU_Sequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPDU_Sequence;
extern asn_SET_OF_specifics_t asn_SPC_EPDU_Sequence_specs_1;
extern asn_TYPE_member_t asn_MBR_EPDU_Sequence_1[1];
extern asn_per_constraints_t asn_PER_type_EPDU_Sequence_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EPDU.h"

#endif	/* _EPDU_Sequence_H_ */
#include <asn_internal.h>
