/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/martin/repos/LPP-Client/asn/LPP.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#include "GNSS-SSR-PhaseBias-r16.h"

static int
memb_ssrUpdateInterval_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_iod_ssr_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ssrUpdateInterval_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_iod_ssr_r16_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_GNSS_SSR_PhaseBias_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GNSS_SSR_PhaseBias_r16, epochTime_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNSS_SystemTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"epochTime-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GNSS_SSR_PhaseBias_r16, ssrUpdateInterval_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ssrUpdateInterval_r16_constr_3,  memb_ssrUpdateInterval_r16_constraint_1 },
		0, 0, /* No default value */
		"ssrUpdateInterval-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GNSS_SSR_PhaseBias_r16, iod_ssr_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_iod_ssr_r16_constr_4,  memb_iod_ssr_r16_constraint_1 },
		0, 0, /* No default value */
		"iod-ssr-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GNSS_SSR_PhaseBias_r16, ssr_PhaseBiasSatList_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SSR_PhaseBiasSatList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssr-PhaseBiasSatList-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GNSS_SSR_PhaseBias_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* epochTime-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssrUpdateInterval-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* iod-ssr-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ssr-PhaseBiasSatList-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_GNSS_SSR_PhaseBias_r16_specs_1 = {
	sizeof(struct GNSS_SSR_PhaseBias_r16),
	offsetof(struct GNSS_SSR_PhaseBias_r16, _asn_ctx),
	asn_MAP_GNSS_SSR_PhaseBias_r16_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GNSS_SSR_PhaseBias_r16 = {
	"GNSS-SSR-PhaseBias-r16",
	"GNSS-SSR-PhaseBias-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1,
	sizeof(asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1)
		/sizeof(asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1[0]), /* 1 */
	asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1)
		/sizeof(asn_DEF_GNSS_SSR_PhaseBias_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GNSS_SSR_PhaseBias_r16_1,
	4,	/* Elements count */
	&asn_SPC_GNSS_SSR_PhaseBias_r16_specs_1	/* Additional specs */
};

