/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/martin/repos/LPP-Client/asn/LPP.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_MutingPattern_r16_H_
#define	_MutingPattern_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MutingPattern_r16_PR {
	MutingPattern_r16_PR_NOTHING,	/* No components present */
	MutingPattern_r16_PR_po2_r16,
	MutingPattern_r16_PR_po4_r16,
	MutingPattern_r16_PR_po6_r16,
	MutingPattern_r16_PR_po8_r16,
	MutingPattern_r16_PR_po16_r16,
	MutingPattern_r16_PR_po32_r16
	/* Extensions may appear below */
	
} MutingPattern_r16_PR;

/* MutingPattern-r16 */
typedef struct MutingPattern_r16 {
	MutingPattern_r16_PR present;
	union MutingPattern_r16_u {
		BIT_STRING_t	 po2_r16;
		BIT_STRING_t	 po4_r16;
		BIT_STRING_t	 po6_r16;
		BIT_STRING_t	 po8_r16;
		BIT_STRING_t	 po16_r16;
		BIT_STRING_t	 po32_r16;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MutingPattern_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MutingPattern_r16;
extern asn_CHOICE_specifics_t asn_SPC_MutingPattern_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MutingPattern_r16_1[6];
extern asn_per_constraints_t asn_PER_type_MutingPattern_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MutingPattern_r16_H_ */
#include <asn_internal.h>
