/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "/home/martin/repos/LPP-Client/asn/ULP-Components.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_RepMode_cap_H_
#define	_RepMode_cap_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RepMode-cap */
typedef struct RepMode_cap {
	BOOLEAN_t	 realtime;
	BOOLEAN_t	 quasirealtime;
	BOOLEAN_t	 batch;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RepMode_cap_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RepMode_cap;
extern asn_SEQUENCE_specifics_t asn_SPC_RepMode_cap_specs_1;
extern asn_TYPE_member_t asn_MBR_RepMode_cap_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RepMode_cap_H_ */
#include <asn_internal.h>
