/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Components"
 * 	found in "/home/martin/repos/LPP-Client/asn/ULP-Components.asn"
 * 	`asn1c -fcompound-names -no-gen-OER -pdu=all -no-gen-example -S /home/martin/repos/LPP-Client/ASN1C/skeletons`
 */

#ifndef	_ULP_Velocity_H_
#define	_ULP_Velocity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Horvel.h"
#include "Horandvervel.h"
#include "Horveluncert.h"
#include "Horandveruncert.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULP_Velocity_PR {
	ULP_Velocity_PR_NOTHING,	/* No components present */
	ULP_Velocity_PR_horvel,
	ULP_Velocity_PR_horandvervel,
	ULP_Velocity_PR_horveluncert,
	ULP_Velocity_PR_horandveruncert
	/* Extensions may appear below */
	
} ULP_Velocity_PR;

/* ULP-Velocity */
typedef struct ULP_Velocity {
	ULP_Velocity_PR present;
	union ULP_Velocity_u {
		Horvel_t	 horvel;
		Horandvervel_t	 horandvervel;
		Horveluncert_t	 horveluncert;
		Horandveruncert_t	 horandveruncert;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULP_Velocity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULP_Velocity;
extern asn_CHOICE_specifics_t asn_SPC_ULP_Velocity_specs_1;
extern asn_TYPE_member_t asn_MBR_ULP_Velocity_1[4];
extern asn_per_constraints_t asn_PER_type_ULP_Velocity_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ULP_Velocity_H_ */
#include <asn_internal.h>
