FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y software-properties-common wget gnupg lsb-release
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main"
RUN apt-get update
RUN apt-get install -y cmake ninja-build libssl-dev libmosquitto-dev git