FROM ubuntu:18.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN apt-get update
RUN apt-get install -y gcc-4.8 g++-4.8
RUN apt-get install -y cmake ninja-build
RUN apt-get install -y libssl-dev
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8