/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_CommonIEsRequestCapabilities_H_
#define	_CommonIEsRequestCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CommonIEsRequestCapabilities__ext1__lpp_message_segmentation_req_r14 {
	CommonIEsRequestCapabilities__ext1__lpp_message_segmentation_req_r14_serverToTarget	= 0,
	CommonIEsRequestCapabilities__ext1__lpp_message_segmentation_req_r14_targetToServer	= 1
} e_CommonIEsRequestCapabilities__ext1__lpp_message_segmentation_req_r14;
typedef enum CommonIEsRequestCapabilities__ext2__remoteUE_IndicationReq_r18 {
	CommonIEsRequestCapabilities__ext2__remoteUE_IndicationReq_r18_true	= 0
} e_CommonIEsRequestCapabilities__ext2__remoteUE_IndicationReq_r18;

/* CommonIEsRequestCapabilities */
typedef struct CommonIEsRequestCapabilities {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct CommonIEsRequestCapabilities__ext1 {
		BIT_STRING_t	*lpp_message_segmentation_req_r14;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct CommonIEsRequestCapabilities__ext2 {
		long	*remoteUE_IndicationReq_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommonIEsRequestCapabilities_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_remoteUE_IndicationReq_r18_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CommonIEsRequestCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_CommonIEsRequestCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_CommonIEsRequestCapabilities_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CommonIEsRequestCapabilities_H_ */
#include <asn_internal.h>
