/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_DL_AoD_MeasCapabilityPerBand_r16_H_
#define	_DL_AoD_MeasCapabilityPerBand_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicatorNR-r16.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16 {
	DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16_supported	= 0
} e_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16;
typedef enum DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16 {
	DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16_supported	= 0
} e_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16;
typedef enum DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17 {
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n1	= 0,
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n2	= 1,
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n4	= 2,
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n8	= 3,
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n16	= 4,
	DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n24	= 5
} e_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17;
typedef enum DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17 {
	DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17_supported	= 0
} e_DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17;
typedef enum DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfLegacyMeasurementInTimeWindow_r18 {
	DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfLegacyMeasurementInTimeWindow_r18_supported	= 0
} e_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfLegacyMeasurementInTimeWindow_r18;

/* DL-AoD-MeasCapabilityPerBand-r16 */
typedef struct DL_AoD_MeasCapabilityPerBand_r16 {
	FreqBandIndicatorNR_r16_t	 freqBandIndicatorNR_r16;
	long	*simul_NR_DL_AoD_DL_TDOA_r16;	/* OPTIONAL */
	long	*simul_NR_DL_AoD_Multi_RTT_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct DL_AoD_MeasCapabilityPerBand_r16__ext1 {
		long	*maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17;	/* OPTIONAL */
		long	*dl_PRS_MeasRRC_Inactive_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct DL_AoD_MeasCapabilityPerBand_r16__ext2 {
		long	*supportOfLegacyMeasurementInTimeWindow_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_AoD_MeasCapabilityPerBand_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_simul_NR_DL_AoD_DL_TDOA_r16_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_simul_NR_DL_AoD_Multi_RTT_r16_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dl_PRS_MeasRRC_Inactive_r17_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_supportOfLegacyMeasurementInTimeWindow_r18_19;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DL_AoD_MeasCapabilityPerBand_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_DL_AoD_MeasCapabilityPerBand_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_AoD_MeasCapabilityPerBand_r16_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DL_AoD_MeasCapabilityPerBand_r16_H_ */
#include <asn_internal.h>
