/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_EPDU_H_
#define	_EPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EPDU-Identifier.h"
#include "EPDU-Body.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EPDU */
typedef struct EPDU {
	EPDU_Identifier_t	 ePDU_Identifier;
	EPDU_Body_t	 ePDU_Body;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_EPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_EPDU_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EPDU_H_ */
#include <asn_internal.h>
