/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_GNSS_ReferenceTime_H_
#define	_GNSS_ReferenceTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GNSS-SystemTime.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GNSS_ReferenceTimeForOneCell;

/* GNSS-ReferenceTime */
typedef struct GNSS_ReferenceTime {
	GNSS_SystemTime_t	 gnss_SystemTime;
	long	*referenceTimeUnc;	/* OPTIONAL */
	struct GNSS_ReferenceTime__gnss_ReferenceTimeForCells {
		A_SEQUENCE_OF(struct GNSS_ReferenceTimeForOneCell) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *gnss_ReferenceTimeForCells;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNSS_ReferenceTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GNSS_ReferenceTime;
extern asn_SEQUENCE_specifics_t asn_SPC_GNSS_ReferenceTime_specs_1;
extern asn_TYPE_member_t asn_MBR_GNSS_ReferenceTime_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _GNSS_ReferenceTime_H_ */
#include <asn_internal.h>
