/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_MBS_AssistanceDataList_r14_H_
#define	_MBS_AssistanceDataList_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBS_AssistanceDataElement_r14;

/* MBS-AssistanceDataList-r14 */
typedef struct MBS_AssistanceDataList_r14 {
	A_SEQUENCE_OF(struct MBS_AssistanceDataElement_r14) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_AssistanceDataList_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_AssistanceDataList_r14;
extern asn_SET_OF_specifics_t asn_SPC_MBS_AssistanceDataList_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_AssistanceDataList_r14_1[1];
extern asn_per_constraints_t asn_PER_type_MBS_AssistanceDataList_r14_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_AssistanceDataList_r14_H_ */
#include <asn_internal.h>
