/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_NR_DL_TDOA_ReportConfig_r16_H_
#define	_NR_DL_TDOA_ReportConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17 {
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n0	= 0,
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n2	= 1,
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n3	= 2,
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n4	= 3,
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n6	= 4,
	NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_n8	= 5
	/*
	 * Enumeration is extensible
	 */
} e_NR_DL_TDOA_ReportConfig_r16__ext1__measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17;
typedef enum NR_DL_TDOA_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17 {
	NR_DL_TDOA_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17_requested	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NR_DL_TDOA_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17;
typedef enum NR_DL_TDOA_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17 {
	NR_DL_TDOA_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17_requested	= 0
} e_NR_DL_TDOA_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17;

/* Forward declarations */
struct NR_DL_PRS_MeasurementTimeWindowsConfig_r18;

/* NR-DL-TDOA-ReportConfig-r16 */
typedef struct NR_DL_TDOA_ReportConfig_r16 {
	long	*maxDL_PRS_RSTD_MeasurementsPerTRP_Pair_r16;	/* OPTIONAL */
	long	*timingReportingGranularityFactor_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct NR_DL_TDOA_ReportConfig_r16__ext1 {
		long	*measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17;	/* OPTIONAL */
		long	*reducedDL_PRS_ProcessingSamples_r17;	/* OPTIONAL */
		long	*lowerRxBeamSweepingFactor_FR2_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct NR_DL_TDOA_ReportConfig_r16__ext2 {
		long	*timingReportingGranularityFactorExt_r18;	/* OPTIONAL */
		struct NR_DL_PRS_MeasurementTimeWindowsConfig_r18	*nr_DL_PRS_MeasurementTimeWindowsConfig_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_DL_TDOA_ReportConfig_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_measureSameDL_PRS_ResourceWithDifferentRxTEGs_r17_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_reducedDL_PRS_ProcessingSamples_r17_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_lowerRxBeamSweepingFactor_FR2_r17_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NR_DL_TDOA_ReportConfig_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_DL_TDOA_ReportConfig_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_DL_TDOA_ReportConfig_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_DL_TDOA_ReportConfig_r16_H_ */
#include <asn_internal.h>
