/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_NR_ECID_ProvideCapabilities_r16_H_
#define	_NR_ECID_ProvideCapabilities_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16 {
	NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_ssrsrpSup	= 0,
	NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_ssrsrqSup	= 1,
	NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_csirsrpSup	= 2,
	NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_csirsrqSup	= 3
} e_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16;
typedef enum NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16 {
	NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16_supported	= 0
} e_NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16;
typedef enum NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16 {
	NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16_supported	= 0
} e_NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16;
typedef enum NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17 {
	NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17_supported	= 0
} e_NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17;

/* Forward declarations */
struct ScheduledLocationTimeSupport_r17;

/* NR-ECID-ProvideCapabilities-r16 */
typedef struct NR_ECID_ProvideCapabilities_r16 {
	BIT_STRING_t	 nr_ECID_MeasSupported_r16;
	long	*periodicalReporting_r16;	/* OPTIONAL */
	long	*triggeredReporting_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct NR_ECID_ProvideCapabilities_r16__ext1 {
		long	*ten_ms_unit_ResponseTime_r17;	/* OPTIONAL */
		struct ScheduledLocationTimeSupport_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_ECID_ProvideCapabilities_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_periodicalReporting_r16_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_triggeredReporting_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ten_ms_unit_ResponseTime_r17_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NR_ECID_ProvideCapabilities_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_ECID_ProvideCapabilities_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_ECID_ProvideCapabilities_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_ECID_ProvideCapabilities_r16_H_ */
#include <asn_internal.h>
