/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#include "NR-On-Demand-DL-PRS-Support-r17.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_nr_on_demand_DL_PRS_InformationSup_r17_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_nr_on_demand_DL_PRS_ConfigurationsSup_r17_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_nr_on_demand_DL_PRS_InformationSup_r17_value2enum_2[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_on_demand_DL_PRS_InformationSup_r17_enum2value_2[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_on_demand_DL_PRS_InformationSup_r17_specs_2 = {
	asn_MAP_nr_on_demand_DL_PRS_InformationSup_r17_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_on_demand_DL_PRS_InformationSup_r17_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_2 = {
	"nr-on-demand-DL-PRS-InformationSup-r17",
	"nr-on-demand-DL-PRS-InformationSup-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2,
	sizeof(asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2)
		/sizeof(asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2[0]) - 1, /* 1 */
	asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2,	/* Same as above */
	sizeof(asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2)
		/sizeof(asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_nr_on_demand_DL_PRS_InformationSup_r17_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_on_demand_DL_PRS_InformationSup_r17_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nr_on_demand_DL_PRS_ConfigurationsSup_r17_value2enum_4[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_nr_on_demand_DL_PRS_ConfigurationsSup_r17_enum2value_4[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_nr_on_demand_DL_PRS_ConfigurationsSup_r17_specs_4 = {
	asn_MAP_nr_on_demand_DL_PRS_ConfigurationsSup_r17_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_nr_on_demand_DL_PRS_ConfigurationsSup_r17_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_4 = {
	"nr-on-demand-DL-PRS-ConfigurationsSup-r17",
	"nr-on-demand-DL-PRS-ConfigurationsSup-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4,
	sizeof(asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4)
		/sizeof(asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4[0]) - 1, /* 1 */
	asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4,	/* Same as above */
	sizeof(asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4)
		/sizeof(asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_nr_on_demand_DL_PRS_ConfigurationsSup_r17_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nr_on_demand_DL_PRS_ConfigurationsSup_r17_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NR_On_Demand_DL_PRS_Support_r17_1[] = {
	{ ATF_POINTER, 2, offsetof(struct NR_On_Demand_DL_PRS_Support_r17, nr_on_demand_DL_PRS_InformationSup_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_on_demand_DL_PRS_InformationSup_r17_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-on-demand-DL-PRS-InformationSup-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_On_Demand_DL_PRS_Support_r17, nr_on_demand_DL_PRS_ConfigurationsSup_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nr_on_demand_DL_PRS_ConfigurationsSup_r17_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-on-demand-DL-PRS-ConfigurationsSup-r17"
		},
};
static const int asn_MAP_NR_On_Demand_DL_PRS_Support_r17_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_On_Demand_DL_PRS_Support_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nr-on-demand-DL-PRS-InformationSup-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nr-on-demand-DL-PRS-ConfigurationsSup-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_NR_On_Demand_DL_PRS_Support_r17_specs_1 = {
	sizeof(struct NR_On_Demand_DL_PRS_Support_r17),
	offsetof(struct NR_On_Demand_DL_PRS_Support_r17, _asn_ctx),
	asn_MAP_NR_On_Demand_DL_PRS_Support_r17_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NR_On_Demand_DL_PRS_Support_r17_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NR_On_Demand_DL_PRS_Support_r17 = {
	"NR-On-Demand-DL-PRS-Support-r17",
	"NR-On-Demand-DL-PRS-Support-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1,
	sizeof(asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1)
		/sizeof(asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1[0]), /* 1 */
	asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1)
		/sizeof(asn_DEF_NR_On_Demand_DL_PRS_Support_r17_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NR_On_Demand_DL_PRS_Support_r17_1,
	2,	/* Elements count */
	&asn_SPC_NR_On_Demand_DL_PRS_Support_r17_specs_1	/* Additional specs */
};

