/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#include "PosSRS-RRC-Inactive-InInitialUL-BWP-r17.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maxNumOfSRSposResourceSets_r17_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maxNumOfPeriodicSRSposResources_r17_constr_28 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maxNumOfPeriodicSRSposResourcesPerSlot_r17_constr_36 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_dummy1_constr_47 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_dummy2_constr_55 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_maxNumOfSRSposResourceSets_r17_value2enum_2[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n8" },
	{ 4,	3,	"n12" },
	{ 5,	3,	"n16" }
};
static const unsigned int asn_MAP_maxNumOfSRSposResourceSets_r17_enum2value_2[] = {
	0,	/* n1(0) */
	4,	/* n12(4) */
	5,	/* n16(5) */
	1,	/* n2(1) */
	2,	/* n4(2) */
	3	/* n8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumOfSRSposResourceSets_r17_specs_2 = {
	asn_MAP_maxNumOfSRSposResourceSets_r17_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumOfSRSposResourceSets_r17_enum2value_2,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfSRSposResourceSets_r17_2 = {
	"maxNumOfSRSposResourceSets-r17",
	"maxNumOfSRSposResourceSets-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2,
	sizeof(asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2)
		/sizeof(asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2[0]) - 1, /* 1 */
	asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2,	/* Same as above */
	sizeof(asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2)
		/sizeof(asn_DEF_maxNumOfSRSposResourceSets_r17_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maxNumOfSRSposResourceSets_r17_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumOfSRSposResourceSets_r17_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_value2enum_9[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n8" },
	{ 4,	3,	"n16" },
	{ 5,	3,	"n32" },
	{ 6,	3,	"n64" }
};
static const unsigned int asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_enum2value_9[] = {
	0,	/* n1(0) */
	4,	/* n16(4) */
	1,	/* n2(1) */
	5,	/* n32(5) */
	2,	/* n4(2) */
	6,	/* n64(6) */
	3	/* n8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_specs_9 = {
	asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_enum2value_9,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_9 = {
	"maxNumOfPeriodicAndSemiPersistentSRSposResources-r17",
	"maxNumOfPeriodicAndSemiPersistentSRSposResources-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9,
	sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9)
		/sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9[0]) - 1, /* 1 */
	asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9,	/* Same as above */
	sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9)
		/sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_tags_9[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_value2enum_17[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" },
	{ 3,	2,	"n4" },
	{ 4,	2,	"n5" },
	{ 5,	2,	"n6" },
	{ 6,	2,	"n8" },
	{ 7,	3,	"n10" },
	{ 8,	3,	"n12" },
	{ 9,	3,	"n14" }
};
static const unsigned int asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_enum2value_17[] = {
	0,	/* n1(0) */
	7,	/* n10(7) */
	8,	/* n12(8) */
	9,	/* n14(9) */
	1,	/* n2(1) */
	2,	/* n3(2) */
	3,	/* n4(3) */
	4,	/* n5(4) */
	5,	/* n6(5) */
	6	/* n8(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_specs_17 = {
	asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_value2enum_17,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_enum2value_17,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_17 = {
	"maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot-r17",
	"maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17,
	sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17)
		/sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17[0]) - 1, /* 1 */
	asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17,	/* Same as above */
	sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17)
		/sizeof(asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_tags_17[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_constr_17,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_specs_17	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumOfPeriodicSRSposResources_r17_value2enum_28[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n8" },
	{ 4,	3,	"n16" },
	{ 5,	3,	"n32" },
	{ 6,	3,	"n64" }
};
static const unsigned int asn_MAP_maxNumOfPeriodicSRSposResources_r17_enum2value_28[] = {
	0,	/* n1(0) */
	4,	/* n16(4) */
	1,	/* n2(1) */
	5,	/* n32(5) */
	2,	/* n4(2) */
	6,	/* n64(6) */
	3	/* n8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumOfPeriodicSRSposResources_r17_specs_28 = {
	asn_MAP_maxNumOfPeriodicSRSposResources_r17_value2enum_28,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumOfPeriodicSRSposResources_r17_enum2value_28,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfPeriodicSRSposResources_r17_28 = {
	"maxNumOfPeriodicSRSposResources-r17",
	"maxNumOfPeriodicSRSposResources-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28,
	sizeof(asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28)
		/sizeof(asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28[0]) - 1, /* 1 */
	asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28,	/* Same as above */
	sizeof(asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28)
		/sizeof(asn_DEF_maxNumOfPeriodicSRSposResources_r17_tags_28[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maxNumOfPeriodicSRSposResources_r17_constr_28,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumOfPeriodicSRSposResources_r17_specs_28	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maxNumOfPeriodicSRSposResourcesPerSlot_r17_value2enum_36[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" },
	{ 3,	2,	"n4" },
	{ 4,	2,	"n5" },
	{ 5,	2,	"n6" },
	{ 6,	2,	"n8" },
	{ 7,	3,	"n10" },
	{ 8,	3,	"n12" },
	{ 9,	3,	"n14" }
};
static const unsigned int asn_MAP_maxNumOfPeriodicSRSposResourcesPerSlot_r17_enum2value_36[] = {
	0,	/* n1(0) */
	7,	/* n10(7) */
	8,	/* n12(8) */
	9,	/* n14(9) */
	1,	/* n2(1) */
	2,	/* n3(2) */
	3,	/* n4(3) */
	4,	/* n5(4) */
	5,	/* n6(5) */
	6	/* n8(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxNumOfPeriodicSRSposResourcesPerSlot_r17_specs_36 = {
	asn_MAP_maxNumOfPeriodicSRSposResourcesPerSlot_r17_value2enum_36,	/* "tag" => N; sorted by tag */
	asn_MAP_maxNumOfPeriodicSRSposResourcesPerSlot_r17_enum2value_36,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_36 = {
	"maxNumOfPeriodicSRSposResourcesPerSlot-r17",
	"maxNumOfPeriodicSRSposResourcesPerSlot-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36,
	sizeof(asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36)
		/sizeof(asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36[0]) - 1, /* 1 */
	asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36,	/* Same as above */
	sizeof(asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36)
		/sizeof(asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_tags_36[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maxNumOfPeriodicSRSposResourcesPerSlot_r17_constr_36,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxNumOfPeriodicSRSposResourcesPerSlot_r17_specs_36	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_dummy1_value2enum_47[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n8" },
	{ 4,	3,	"n16" },
	{ 5,	3,	"n32" },
	{ 6,	3,	"n64" }
};
static const unsigned int asn_MAP_dummy1_enum2value_47[] = {
	0,	/* n1(0) */
	4,	/* n16(4) */
	1,	/* n2(1) */
	5,	/* n32(5) */
	2,	/* n4(2) */
	6,	/* n64(6) */
	3	/* n8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_dummy1_specs_47 = {
	asn_MAP_dummy1_value2enum_47,	/* "tag" => N; sorted by tag */
	asn_MAP_dummy1_enum2value_47,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_dummy1_tags_47[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dummy1_47 = {
	"dummy1",
	"dummy1",
	&asn_OP_NativeEnumerated,
	asn_DEF_dummy1_tags_47,
	sizeof(asn_DEF_dummy1_tags_47)
		/sizeof(asn_DEF_dummy1_tags_47[0]) - 1, /* 1 */
	asn_DEF_dummy1_tags_47,	/* Same as above */
	sizeof(asn_DEF_dummy1_tags_47)
		/sizeof(asn_DEF_dummy1_tags_47[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_dummy1_constr_47,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_dummy1_specs_47	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_dummy2_value2enum_55[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" },
	{ 3,	2,	"n4" },
	{ 4,	2,	"n5" },
	{ 5,	2,	"n6" },
	{ 6,	2,	"n8" },
	{ 7,	3,	"n10" },
	{ 8,	3,	"n12" },
	{ 9,	3,	"n14" }
};
static const unsigned int asn_MAP_dummy2_enum2value_55[] = {
	0,	/* n1(0) */
	7,	/* n10(7) */
	8,	/* n12(8) */
	9,	/* n14(9) */
	1,	/* n2(1) */
	2,	/* n3(2) */
	3,	/* n4(3) */
	4,	/* n5(4) */
	5,	/* n6(5) */
	6	/* n8(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_dummy2_specs_55 = {
	asn_MAP_dummy2_value2enum_55,	/* "tag" => N; sorted by tag */
	asn_MAP_dummy2_enum2value_55,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_dummy2_tags_55[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dummy2_55 = {
	"dummy2",
	"dummy2",
	&asn_OP_NativeEnumerated,
	asn_DEF_dummy2_tags_55,
	sizeof(asn_DEF_dummy2_tags_55)
		/sizeof(asn_DEF_dummy2_tags_55[0]) - 1, /* 1 */
	asn_DEF_dummy2_tags_55,	/* Same as above */
	sizeof(asn_DEF_dummy2_tags_55)
		/sizeof(asn_DEF_dummy2_tags_55[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_dummy2_constr_55,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_dummy2_specs_55	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_1[] = {
	{ ATF_POINTER, 7, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, maxNumOfSRSposResourceSets_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumOfSRSposResourceSets_r17_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfSRSposResourceSets-r17"
		},
	{ ATF_POINTER, 6, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, maxNumOfPeriodicAndSemiPersistentSRSposResources_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfPeriodicAndSemiPersistentSRSposResources-r17"
		},
	{ ATF_POINTER, 5, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot-r17"
		},
	{ ATF_POINTER, 4, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, maxNumOfPeriodicSRSposResources_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumOfPeriodicSRSposResources_r17_28,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfPeriodicSRSposResources-r17"
		},
	{ ATF_POINTER, 3, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, maxNumOfPeriodicSRSposResourcesPerSlot_r17),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxNumOfPeriodicSRSposResourcesPerSlot_r17_36,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfPeriodicSRSposResourcesPerSlot-r17"
		},
	{ ATF_POINTER, 2, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, dummy1),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_dummy1_47,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dummy1"
		},
	{ ATF_POINTER, 1, offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, dummy2),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_dummy2_55,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dummy2"
		},
};
static const int asn_MAP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxNumOfSRSposResourceSets-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxNumOfPeriodicAndSemiPersistentSRSposResources-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* maxNumOfPeriodicSRSposResources-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* maxNumOfPeriodicSRSposResourcesPerSlot-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dummy1 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* dummy2 */
};
asn_SEQUENCE_specifics_t asn_SPC_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_specs_1 = {
	sizeof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17),
	offsetof(struct PosSRS_RRC_Inactive_InInitialUL_BWP_r17, _asn_ctx),
	asn_MAP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17 = {
	"PosSRS-RRC-Inactive-InInitialUL-BWP-r17",
	"PosSRS-RRC-Inactive-InInitialUL-BWP-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1,
	sizeof(asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1)
		/sizeof(asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1[0]), /* 1 */
	asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1)
		/sizeof(asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_1,
	7,	/* Elements count */
	&asn_SPC_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_specs_1	/* Additional specs */
};

