/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#include "PRS-BWA-ThreeContiguousIntrabandInMG-r18.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  14 }	/* (0..14) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_constr_27 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_dl_PRS_BufferTypeOfBWA_r18_constr_40 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_constr_44 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  17 }	/* (0..17) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_constr_63 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_scs15_r18_constr_75 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_scs30_r18_constr_87 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_scs60_r18_constr_99 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_scs60_r18_constr_112 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_scs120_r18_constr_124 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_value2enum_2[] = {
	{ 0,	5,	"mhz15" },
	{ 1,	5,	"mhz20" },
	{ 2,	5,	"mhz30" },
	{ 3,	5,	"mhz40" },
	{ 4,	5,	"mhz50" },
	{ 5,	5,	"mhz60" },
	{ 6,	5,	"mhz80" },
	{ 7,	6,	"mhz100" },
	{ 8,	6,	"mhz120" },
	{ 9,	6,	"mhz140" },
	{ 10,	6,	"mhz150" },
	{ 11,	6,	"mhz180" },
	{ 12,	6,	"mhz200" },
	{ 13,	6,	"mhz240" },
	{ 14,	6,	"mhz300" }
};
static const unsigned int asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_enum2value_2[] = {
	7,	/* mhz100(7) */
	8,	/* mhz120(8) */
	9,	/* mhz140(9) */
	0,	/* mhz15(0) */
	10,	/* mhz150(10) */
	11,	/* mhz180(11) */
	1,	/* mhz20(1) */
	12,	/* mhz200(12) */
	13,	/* mhz240(13) */
	2,	/* mhz30(2) */
	14,	/* mhz300(14) */
	3,	/* mhz40(3) */
	4,	/* mhz50(4) */
	5,	/* mhz60(5) */
	6	/* mhz80(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_specs_2 = {
	asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_enum2value_2,	/* N => "tag"; sorted by N */
	15,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_2 = {
	"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR1-r18",
	"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR1-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2,
	sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2)
		/sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2[0]) - 1, /* 1 */
	asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2,	/* Same as above */
	sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2)
		/sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_value2enum_18[] = {
	{ 0,	6,	"mhz150" },
	{ 1,	6,	"mhz200" },
	{ 2,	6,	"mhz300" },
	{ 3,	6,	"mhz400" },
	{ 4,	6,	"mhz600" },
	{ 5,	6,	"mhz800" },
	{ 6,	7,	"mhz1000" },
	{ 7,	7,	"mhz1200" }
};
static const unsigned int asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_enum2value_18[] = {
	6,	/* mhz1000(6) */
	7,	/* mhz1200(7) */
	0,	/* mhz150(0) */
	1,	/* mhz200(1) */
	2,	/* mhz300(2) */
	3,	/* mhz400(3) */
	4,	/* mhz600(4) */
	5	/* mhz800(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_specs_18 = {
	asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_enum2value_18,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_18 = {
	"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR2-r18",
	"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR2-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18,
	sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18)
		/sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18[0]) - 1, /* 1 */
	asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18,	/* Same as above */
	sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18)
		/sizeof(asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_tags_18[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_constr_18,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_value2enum_27[] = {
	{ 0,	4,	"mhz5" },
	{ 1,	5,	"mhz10" },
	{ 2,	5,	"mhz20" },
	{ 3,	5,	"mhz40" },
	{ 4,	5,	"mhz50" },
	{ 5,	5,	"mhz80" },
	{ 6,	6,	"mhz100" }
};
static const unsigned int asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_enum2value_27[] = {
	1,	/* mhz10(1) */
	6,	/* mhz100(6) */
	2,	/* mhz20(2) */
	3,	/* mhz40(3) */
	0,	/* mhz5(0) */
	4,	/* mhz50(4) */
	5	/* mhz80(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_specs_27 = {
	asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_enum2value_27,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_27 = {
	"maximumOfDL-PRS-BandwidthPerPFL-FR1-r18",
	"maximumOfDL-PRS-BandwidthPerPFL-FR1-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27,
	sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27)
		/sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27[0]) - 1, /* 1 */
	asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27,	/* Same as above */
	sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27)
		/sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_tags_27[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_constr_27,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_specs_27	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_value2enum_35[] = {
	{ 0,	5,	"mhz50" },
	{ 1,	6,	"mhz100" },
	{ 2,	6,	"mhz200" },
	{ 3,	6,	"mhz400" }
};
static const unsigned int asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_enum2value_35[] = {
	1,	/* mhz100(1) */
	2,	/* mhz200(2) */
	3,	/* mhz400(3) */
	0	/* mhz50(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_specs_35 = {
	asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_value2enum_35,	/* "tag" => N; sorted by tag */
	asn_MAP_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_enum2value_35,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_35 = {
	"maximumOfDL-PRS-BandwidthPerPFL-FR2-r18",
	"maximumOfDL-PRS-BandwidthPerPFL-FR2-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35,
	sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35)
		/sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35[0]) - 1, /* 1 */
	asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35,	/* Same as above */
	sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35)
		/sizeof(asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_tags_35[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_constr_35,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_specs_35	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_dl_PRS_BufferTypeOfBWA_r18_value2enum_40[] = {
	{ 0,	5,	"type1" },
	{ 1,	5,	"type2" }
};
static const unsigned int asn_MAP_dl_PRS_BufferTypeOfBWA_r18_enum2value_40[] = {
	0,	/* type1(0) */
	1	/* type2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_dl_PRS_BufferTypeOfBWA_r18_specs_40 = {
	asn_MAP_dl_PRS_BufferTypeOfBWA_r18_value2enum_40,	/* "tag" => N; sorted by tag */
	asn_MAP_dl_PRS_BufferTypeOfBWA_r18_enum2value_40,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_PRS_BufferTypeOfBWA_r18_40 = {
	"dl-PRS-BufferTypeOfBWA-r18",
	"dl-PRS-BufferTypeOfBWA-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40,
	sizeof(asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40)
		/sizeof(asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40[0]) - 1, /* 1 */
	asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40,	/* Same as above */
	sizeof(asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40)
		/sizeof(asn_DEF_dl_PRS_BufferTypeOfBWA_r18_tags_40[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_dl_PRS_BufferTypeOfBWA_r18_constr_40,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_dl_PRS_BufferTypeOfBWA_r18_specs_40	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_value2enum_44[] = {
	{ 0,	8,	"msDot125" },
	{ 1,	7,	"msDot25" },
	{ 2,	6,	"msDot5" },
	{ 3,	3,	"ms1" },
	{ 4,	3,	"ms2" },
	{ 5,	3,	"ms4" },
	{ 6,	3,	"ms6" },
	{ 7,	3,	"ms8" },
	{ 8,	4,	"ms12" },
	{ 9,	4,	"ms16" },
	{ 10,	4,	"ms20" },
	{ 11,	4,	"ms25" },
	{ 12,	4,	"ms30" },
	{ 13,	4,	"ms32" },
	{ 14,	4,	"ms35" },
	{ 15,	4,	"ms40" },
	{ 16,	4,	"ms45" },
	{ 17,	4,	"ms50" }
};
static const unsigned int asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_enum2value_44[] = {
	3,	/* ms1(3) */
	8,	/* ms12(8) */
	9,	/* ms16(9) */
	4,	/* ms2(4) */
	10,	/* ms20(10) */
	11,	/* ms25(11) */
	12,	/* ms30(12) */
	13,	/* ms32(13) */
	14,	/* ms35(14) */
	5,	/* ms4(5) */
	15,	/* ms40(15) */
	16,	/* ms45(16) */
	17,	/* ms50(17) */
	6,	/* ms6(6) */
	7,	/* ms8(7) */
	0,	/* msDot125(0) */
	1,	/* msDot25(1) */
	2	/* msDot5(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_specs_44 = {
	asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_value2enum_44,	/* "tag" => N; sorted by tag */
	asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_enum2value_44,	/* N => "tag"; sorted by N */
	18,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_44 = {
	"prs-durationOfThreePRS-BWA-ProcessingSymbolsN-r18",
	"prs-durationOfThreePRS-BWA-ProcessingSymbolsN-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44,
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44[0]) - 1, /* 1 */
	asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44,	/* Same as above */
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_tags_44[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_constr_44,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_specs_44	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_value2enum_63[] = {
	{ 0,	3,	"ms8" },
	{ 1,	4,	"ms16" },
	{ 2,	4,	"ms20" },
	{ 3,	4,	"ms30" },
	{ 4,	4,	"ms40" },
	{ 5,	4,	"ms80" },
	{ 6,	5,	"ms160" },
	{ 7,	5,	"ms320" },
	{ 8,	5,	"ms640" },
	{ 9,	6,	"ms1280" }
};
static const unsigned int asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_enum2value_63[] = {
	9,	/* ms1280(9) */
	1,	/* ms16(1) */
	6,	/* ms160(6) */
	2,	/* ms20(2) */
	3,	/* ms30(3) */
	7,	/* ms320(7) */
	4,	/* ms40(4) */
	8,	/* ms640(8) */
	0,	/* ms8(0) */
	5	/* ms80(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_specs_63 = {
	asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_value2enum_63,	/* "tag" => N; sorted by tag */
	asn_MAP_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_enum2value_63,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_63 = {
	"prs-durationOfThreePRS-BWA-ProcessingSymbolsT-r18",
	"prs-durationOfThreePRS-BWA-ProcessingSymbolsT-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63,
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63[0]) - 1, /* 1 */
	asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63,	/* Same as above */
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_tags_63[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_constr_63,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_specs_63	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_prs_durationOfThreePRS_BWA_Processing_r18_43[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__prs_durationOfThreePRS_BWA_Processing_r18, prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsN_r18_44,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"prs-durationOfThreePRS-BWA-ProcessingSymbolsN-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__prs_durationOfThreePRS_BWA_Processing_r18, prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_prs_durationOfThreePRS_BWA_ProcessingSymbolsT_r18_63,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"prs-durationOfThreePRS-BWA-ProcessingSymbolsT-r18"
		},
};
static const ber_tlv_tag_t asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_prs_durationOfThreePRS_BWA_Processing_r18_tag2el_43[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* prs-durationOfThreePRS-BWA-ProcessingSymbolsN-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* prs-durationOfThreePRS-BWA-ProcessingSymbolsT-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_prs_durationOfThreePRS_BWA_Processing_r18_specs_43 = {
	sizeof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__prs_durationOfThreePRS_BWA_Processing_r18),
	offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__prs_durationOfThreePRS_BWA_Processing_r18, _asn_ctx),
	asn_MAP_prs_durationOfThreePRS_BWA_Processing_r18_tag2el_43,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_43 = {
	"prs-durationOfThreePRS-BWA-Processing-r18",
	"prs-durationOfThreePRS-BWA-Processing-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43,
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43[0]) - 1, /* 1 */
	asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43,	/* Same as above */
	sizeof(asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43)
		/sizeof(asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_tags_43[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_prs_durationOfThreePRS_BWA_Processing_r18_43,
	2,	/* Elements count */
	&asn_SPC_prs_durationOfThreePRS_BWA_Processing_r18_specs_43	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_scs15_r18_value2enum_75[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n6" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" },
	{ 6,	3,	"n16" },
	{ 7,	3,	"n24" },
	{ 8,	3,	"n32" },
	{ 9,	3,	"n48" },
	{ 10,	3,	"n64" }
};
static const unsigned int asn_MAP_scs15_r18_enum2value_75[] = {
	0,	/* n1(0) */
	5,	/* n12(5) */
	6,	/* n16(6) */
	1,	/* n2(1) */
	7,	/* n24(7) */
	8,	/* n32(8) */
	2,	/* n4(2) */
	9,	/* n48(9) */
	3,	/* n6(3) */
	10,	/* n64(10) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_scs15_r18_specs_75 = {
	asn_MAP_scs15_r18_value2enum_75,	/* "tag" => N; sorted by tag */
	asn_MAP_scs15_r18_enum2value_75,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_scs15_r18_tags_75[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scs15_r18_75 = {
	"scs15-r18",
	"scs15-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_scs15_r18_tags_75,
	sizeof(asn_DEF_scs15_r18_tags_75)
		/sizeof(asn_DEF_scs15_r18_tags_75[0]) - 1, /* 1 */
	asn_DEF_scs15_r18_tags_75,	/* Same as above */
	sizeof(asn_DEF_scs15_r18_tags_75)
		/sizeof(asn_DEF_scs15_r18_tags_75[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_scs15_r18_constr_75,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_scs15_r18_specs_75	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_scs30_r18_value2enum_87[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n6" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" },
	{ 6,	3,	"n16" },
	{ 7,	3,	"n24" },
	{ 8,	3,	"n32" },
	{ 9,	3,	"n48" },
	{ 10,	3,	"n64" }
};
static const unsigned int asn_MAP_scs30_r18_enum2value_87[] = {
	0,	/* n1(0) */
	5,	/* n12(5) */
	6,	/* n16(6) */
	1,	/* n2(1) */
	7,	/* n24(7) */
	8,	/* n32(8) */
	2,	/* n4(2) */
	9,	/* n48(9) */
	3,	/* n6(3) */
	10,	/* n64(10) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_scs30_r18_specs_87 = {
	asn_MAP_scs30_r18_value2enum_87,	/* "tag" => N; sorted by tag */
	asn_MAP_scs30_r18_enum2value_87,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_scs30_r18_tags_87[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scs30_r18_87 = {
	"scs30-r18",
	"scs30-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_scs30_r18_tags_87,
	sizeof(asn_DEF_scs30_r18_tags_87)
		/sizeof(asn_DEF_scs30_r18_tags_87[0]) - 1, /* 1 */
	asn_DEF_scs30_r18_tags_87,	/* Same as above */
	sizeof(asn_DEF_scs30_r18_tags_87)
		/sizeof(asn_DEF_scs30_r18_tags_87[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_scs30_r18_constr_87,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_scs30_r18_specs_87	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_scs60_r18_value2enum_99[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n6" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" },
	{ 6,	3,	"n16" },
	{ 7,	3,	"n24" },
	{ 8,	3,	"n32" },
	{ 9,	3,	"n48" },
	{ 10,	3,	"n64" }
};
static const unsigned int asn_MAP_scs60_r18_enum2value_99[] = {
	0,	/* n1(0) */
	5,	/* n12(5) */
	6,	/* n16(6) */
	1,	/* n2(1) */
	7,	/* n24(7) */
	8,	/* n32(8) */
	2,	/* n4(2) */
	9,	/* n48(9) */
	3,	/* n6(3) */
	10,	/* n64(10) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_scs60_r18_specs_99 = {
	asn_MAP_scs60_r18_value2enum_99,	/* "tag" => N; sorted by tag */
	asn_MAP_scs60_r18_enum2value_99,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_scs60_r18_tags_99[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scs60_r18_99 = {
	"scs60-r18",
	"scs60-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_scs60_r18_tags_99,
	sizeof(asn_DEF_scs60_r18_tags_99)
		/sizeof(asn_DEF_scs60_r18_tags_99[0]) - 1, /* 1 */
	asn_DEF_scs60_r18_tags_99,	/* Same as above */
	sizeof(asn_DEF_scs60_r18_tags_99)
		/sizeof(asn_DEF_scs60_r18_tags_99[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_scs60_r18_constr_99,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_scs60_r18_specs_99	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_74[] = {
	{ ATF_POINTER, 3, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18, scs15_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_scs15_r18_75,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"scs15-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18, scs30_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_scs30_r18_87,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"scs30-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18, scs60_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_scs60_r18_99,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"scs60-r18"
		},
};
static const int asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_oms_74[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tag2el_74[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scs15-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* scs30-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* scs60-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_specs_74 = {
	sizeof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18),
	offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18, _asn_ctx),
	asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tag2el_74,
	3,	/* Count of tags in the map */
	asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_oms_74,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_74 = {
	"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR1-r18",
	"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR1-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74,
	sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74)
		/sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74[0]) - 1, /* 1 */
	asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74,	/* Same as above */
	sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74)
		/sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_tags_74[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_74,
	3,	/* Elements count */
	&asn_SPC_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_specs_74	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_scs60_r18_value2enum_112[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n6" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" },
	{ 6,	3,	"n16" },
	{ 7,	3,	"n24" },
	{ 8,	3,	"n32" },
	{ 9,	3,	"n48" },
	{ 10,	3,	"n64" }
};
static const unsigned int asn_MAP_scs60_r18_enum2value_112[] = {
	0,	/* n1(0) */
	5,	/* n12(5) */
	6,	/* n16(6) */
	1,	/* n2(1) */
	7,	/* n24(7) */
	8,	/* n32(8) */
	2,	/* n4(2) */
	9,	/* n48(9) */
	3,	/* n6(3) */
	10,	/* n64(10) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_scs60_r18_specs_112 = {
	asn_MAP_scs60_r18_value2enum_112,	/* "tag" => N; sorted by tag */
	asn_MAP_scs60_r18_enum2value_112,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_scs60_r18_tags_112[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scs60_r18_112 = {
	"scs60-r18",
	"scs60-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_scs60_r18_tags_112,
	sizeof(asn_DEF_scs60_r18_tags_112)
		/sizeof(asn_DEF_scs60_r18_tags_112[0]) - 1, /* 1 */
	asn_DEF_scs60_r18_tags_112,	/* Same as above */
	sizeof(asn_DEF_scs60_r18_tags_112)
		/sizeof(asn_DEF_scs60_r18_tags_112[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_scs60_r18_constr_112,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_scs60_r18_specs_112	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_scs120_r18_value2enum_124[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n4" },
	{ 3,	2,	"n6" },
	{ 4,	2,	"n8" },
	{ 5,	3,	"n12" },
	{ 6,	3,	"n16" },
	{ 7,	3,	"n24" },
	{ 8,	3,	"n32" },
	{ 9,	3,	"n48" },
	{ 10,	3,	"n64" }
};
static const unsigned int asn_MAP_scs120_r18_enum2value_124[] = {
	0,	/* n1(0) */
	5,	/* n12(5) */
	6,	/* n16(6) */
	1,	/* n2(1) */
	7,	/* n24(7) */
	8,	/* n32(8) */
	2,	/* n4(2) */
	9,	/* n48(9) */
	3,	/* n6(3) */
	10,	/* n64(10) */
	4	/* n8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_scs120_r18_specs_124 = {
	asn_MAP_scs120_r18_value2enum_124,	/* "tag" => N; sorted by tag */
	asn_MAP_scs120_r18_enum2value_124,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_scs120_r18_tags_124[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scs120_r18_124 = {
	"scs120-r18",
	"scs120-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_scs120_r18_tags_124,
	sizeof(asn_DEF_scs120_r18_tags_124)
		/sizeof(asn_DEF_scs120_r18_tags_124[0]) - 1, /* 1 */
	asn_DEF_scs120_r18_tags_124,	/* Same as above */
	sizeof(asn_DEF_scs120_r18_tags_124)
		/sizeof(asn_DEF_scs120_r18_tags_124[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_scs120_r18_constr_124,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_scs120_r18_specs_124	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_111[] = {
	{ ATF_POINTER, 2, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18, scs60_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_scs60_r18_112,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"scs60-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18, scs120_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_scs120_r18_124,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"scs120-r18"
		},
};
static const int asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_oms_111[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tag2el_111[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scs60-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* scs120-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_specs_111 = {
	sizeof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18),
	offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18__maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18, _asn_ctx),
	asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tag2el_111,
	2,	/* Count of tags in the map */
	asn_MAP_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_oms_111,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_111 = {
	"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR2-r18",
	"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR2-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111,
	sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111)
		/sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111[0]) - 1, /* 1 */
	asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111,	/* Same as above */
	sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111)
		/sizeof(asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_tags_111[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_111,
	2,	/* Elements count */
	&asn_SPC_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_specs_111	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PRS_BWA_ThreeContiguousIntrabandInMG_r18_1[] = {
	{ ATF_POINTER, 4, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR1_r18_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR1-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maximumOfThreeAggregatedDL_PRS_Bandwidth_FR2_r18_18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maximumOfThreeAggregatedDL-PRS-Bandwidth-FR2-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maximumOfDL_PRS_BandwidthPerPFL_FR1_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR1_r18_27,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maximumOfDL-PRS-BandwidthPerPFL-FR1-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maximumOfDL_PRS_BandwidthPerPFL_FR2_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maximumOfDL_PRS_BandwidthPerPFL_FR2_r18_35,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maximumOfDL-PRS-BandwidthPerPFL-FR2-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, dl_PRS_BufferTypeOfBWA_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_dl_PRS_BufferTypeOfBWA_r18_40,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dl-PRS-BufferTypeOfBWA-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, prs_durationOfThreePRS_BWA_Processing_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_prs_durationOfThreePRS_BWA_Processing_r18_43,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"prs-durationOfThreePRS-BWA-Processing-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR1_r18_74,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR1-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_maxNumOfAggregatedDL_PRS_ResourcePerSlot_FR2_r18_111,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR2-r18"
		},
};
static const int asn_MAP_PRS_BWA_ThreeContiguousIntrabandInMG_r18_oms_1[] = { 0, 1, 2, 3, 5 };
static const ber_tlv_tag_t asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maximumOfThreeAggregatedDL-PRS-Bandwidth-FR1-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maximumOfThreeAggregatedDL-PRS-Bandwidth-FR2-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* maximumOfDL-PRS-BandwidthPerPFL-FR1-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* maximumOfDL-PRS-BandwidthPerPFL-FR2-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dl-PRS-BufferTypeOfBWA-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* prs-durationOfThreePRS-BWA-Processing-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR1-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* maxNumOfAggregatedDL-PRS-ResourcePerSlot-FR2-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_PRS_BWA_ThreeContiguousIntrabandInMG_r18_specs_1 = {
	sizeof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18),
	offsetof(struct PRS_BWA_ThreeContiguousIntrabandInMG_r18, _asn_ctx),
	asn_MAP_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_PRS_BWA_ThreeContiguousIntrabandInMG_r18_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18 = {
	"PRS-BWA-ThreeContiguousIntrabandInMG-r18",
	"PRS-BWA-ThreeContiguousIntrabandInMG-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1,
	sizeof(asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1)
		/sizeof(asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1[0]), /* 1 */
	asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1)
		/sizeof(asn_DEF_PRS_BWA_ThreeContiguousIntrabandInMG_r18_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PRS_BWA_ThreeContiguousIntrabandInMG_r18_1,
	8,	/* Elements count */
	&asn_SPC_PRS_BWA_ThreeContiguousIntrabandInMG_r18_specs_1	/* Additional specs */
};

