/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#ifndef	_SpatialDelta_r18_H_
#define	_SpatialDelta_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpatialDelta_r18 {
	SpatialDelta_r18_n1	= 0,
	SpatialDelta_r18_n2	= 1,
	SpatialDelta_r18_n3	= 2,
	SpatialDelta_r18_n4	= 3,
	SpatialDelta_r18_n5	= 4,
	SpatialDelta_r18_n10	= 5,
	SpatialDelta_r18_n20	= 6,
	SpatialDelta_r18_n50	= 7,
	SpatialDelta_r18_n100	= 8
} e_SpatialDelta_r18;

/* SpatialDelta-r18 */
typedef long	 SpatialDelta_r18_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SpatialDelta_r18_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SpatialDelta_r18;
extern const asn_INTEGER_specifics_t asn_SPC_SpatialDelta_r18_specs_1;
asn_struct_free_f SpatialDelta_r18_free;
asn_constr_check_f SpatialDelta_r18_constraint;
xer_type_decoder_f SpatialDelta_r18_decode_xer;
xer_type_encoder_f SpatialDelta_r18_encode_xer;
jer_type_encoder_f SpatialDelta_r18_encode_jer;
per_type_decoder_f SpatialDelta_r18_decode_uper;
per_type_encoder_f SpatialDelta_r18_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpatialDelta_r18_H_ */
#include <asn_internal.h>
