/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "src/LPP-PDU-Definitions.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -no-gen-example -pdu=all -gen-XER -gen-JER -no-gen-OER -gen-UPER -no-gen-APER -no-gen-BER -no-gen-print -no-gen-random-fill -D lpp_generated/ -S empty_skeleton/`
 */

#include "SRS-CapabilityPerBand-r16.h"

#include "OLPC-SRS-Pos-r16.h"
#include "SpatialRelationsSRS-Pos-r16.h"
#include "PosSRS-RRC-Inactive-InInitialUL-BWP-r17.h"
#include "PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17.h"
#include "PosSRS-SP-RRC-Inactive-InInitialUL-BWP-r17.h"
#include "PosSRS-TxFrequencyHoppingRRC-Connected-r18.h"
#include "PosSRS-TxFrequencyHoppingRRC-Inactive-r18.h"
#include "PosSRS-BWA-RRC-Inactive-r18.h"
#include "PosSRS-BWA-RRC-Connected-r18.h"
#include "PosSRS-BWA-IndependentCA-RRC-Connected-r18.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_posSRS_TxFH_WithTimeWindow_r18_constr_24 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_ext1_6[] = {
	{ ATF_POINTER, 4, offsetof(struct SRS_CapabilityPerBand_r16__ext1, posSRS_RRC_Inactive_InInitialUL_BWP_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_RRC_Inactive_InInitialUL_BWP_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-RRC-Inactive-InInitialUL-BWP-r17"
		},
	{ ATF_POINTER, 3, offsetof(struct SRS_CapabilityPerBand_r16__ext1, posSRS_RRC_Inactive_OutsideInitialUL_BWP_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-RRC-Inactive-OutsideInitialUL-BWP-r17"
		},
	{ ATF_POINTER, 2, offsetof(struct SRS_CapabilityPerBand_r16__ext1, olpc_SRS_PosRRC_Inactive_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OLPC_SRS_Pos_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"olpc-SRS-PosRRC-Inactive-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct SRS_CapabilityPerBand_r16__ext1, spatialRelationsSRS_PosRRC_Inactive_r17),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpatialRelationsSRS_Pos_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"spatialRelationsSRS-PosRRC-Inactive-r17"
		},
};
static const int asn_MAP_ext1_oms_6[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ext1_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext1_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* posSRS-RRC-Inactive-InInitialUL-BWP-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* posSRS-RRC-Inactive-OutsideInitialUL-BWP-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* olpc-SRS-PosRRC-Inactive-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* spatialRelationsSRS-PosRRC-Inactive-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext1_specs_6 = {
	sizeof(struct SRS_CapabilityPerBand_r16__ext1),
	offsetof(struct SRS_CapabilityPerBand_r16__ext1, _asn_ctx),
	asn_MAP_ext1_tag2el_6,
	4,	/* Count of tags in the map */
	asn_MAP_ext1_oms_6,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext1_6 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_ext1_tags_6,
	sizeof(asn_DEF_ext1_tags_6)
		/sizeof(asn_DEF_ext1_tags_6[0]) - 1, /* 1 */
	asn_DEF_ext1_tags_6,	/* Same as above */
	sizeof(asn_DEF_ext1_tags_6)
		/sizeof(asn_DEF_ext1_tags_6[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext1_6,
	4,	/* Elements count */
	&asn_SPC_ext1_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ext2_11[] = {
	{ ATF_POINTER, 1, offsetof(struct SRS_CapabilityPerBand_r16__ext2, posSRS_SP_RRC_Inactive_InInitialUL_BWP_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_SP_RRC_Inactive_InInitialUL_BWP_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-SP-RRC-Inactive-InInitialUL-BWP-r17"
		},
};
static const int asn_MAP_ext2_oms_11[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ext2_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext2_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* posSRS-SP-RRC-Inactive-InInitialUL-BWP-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext2_specs_11 = {
	sizeof(struct SRS_CapabilityPerBand_r16__ext2),
	offsetof(struct SRS_CapabilityPerBand_r16__ext2, _asn_ctx),
	asn_MAP_ext2_tag2el_11,
	1,	/* Count of tags in the map */
	asn_MAP_ext2_oms_11,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext2_11 = {
	"ext2",
	"ext2",
	&asn_OP_SEQUENCE,
	asn_DEF_ext2_tags_11,
	sizeof(asn_DEF_ext2_tags_11)
		/sizeof(asn_DEF_ext2_tags_11[0]) - 1, /* 1 */
	asn_DEF_ext2_tags_11,	/* Same as above */
	sizeof(asn_DEF_ext2_tags_11)
		/sizeof(asn_DEF_ext2_tags_11[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext2_11,
	1,	/* Elements count */
	&asn_SPC_ext2_specs_11	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_value2enum_14[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_enum2value_14[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_specs_14 = {
	asn_MAP_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_enum2value_14,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_14 = {
	"posSRS-Preconfigured-RRC-InactiveInitialUL-BWP-r18",
	"posSRS-Preconfigured-RRC-InactiveInitialUL-BWP-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14,
	sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14)
		/sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14[0]) - 1, /* 1 */
	asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14,	/* Same as above */
	sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14)
		/sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_tags_14[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_constr_14,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_value2enum_16[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_enum2value_16[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_specs_16 = {
	asn_MAP_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_value2enum_16,	/* "tag" => N; sorted by tag */
	asn_MAP_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_enum2value_16,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_16 = {
	"posSRS-Preconfigured-RRC-InactiveOutsideInitialUL-BWP-r18",
	"posSRS-Preconfigured-RRC-InactiveOutsideInitialUL-BWP-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16,
	sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16)
		/sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16[0]) - 1, /* 1 */
	asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16,	/* Same as above */
	sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16)
		/sizeof(asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_tags_16[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_constr_16,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_specs_16	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_value2enum_18[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_enum2value_18[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_specs_18 = {
	asn_MAP_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_enum2value_18,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_18 = {
	"posSRS-ValidityAreaRRC-InactiveInitialUL-BWP-r18",
	"posSRS-ValidityAreaRRC-InactiveInitialUL-BWP-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18,
	sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18)
		/sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18[0]) - 1, /* 1 */
	asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18,	/* Same as above */
	sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18)
		/sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_tags_18[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_constr_18,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_value2enum_20[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_enum2value_20[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_specs_20 = {
	asn_MAP_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_enum2value_20,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_20 = {
	"posSRS-ValidityAreaRRC-InactiveOutsideInitialUL-BWP-r18",
	"posSRS-ValidityAreaRRC-InactiveOutsideInitialUL-BWP-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20,
	sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20)
		/sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20[0]) - 1, /* 1 */
	asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20,	/* Same as above */
	sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20)
		/sizeof(asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_tags_20[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_constr_20,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_specs_20	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_posSRS_TxFH_WithTimeWindow_r18_value2enum_24[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_posSRS_TxFH_WithTimeWindow_r18_enum2value_24[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_posSRS_TxFH_WithTimeWindow_r18_specs_24 = {
	asn_MAP_posSRS_TxFH_WithTimeWindow_r18_value2enum_24,	/* "tag" => N; sorted by tag */
	asn_MAP_posSRS_TxFH_WithTimeWindow_r18_enum2value_24,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_posSRS_TxFH_WithTimeWindow_r18_24 = {
	"posSRS-TxFH-WithTimeWindow-r18",
	"posSRS-TxFH-WithTimeWindow-r18",
	&asn_OP_NativeEnumerated,
	asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24,
	sizeof(asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24)
		/sizeof(asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24[0]) - 1, /* 1 */
	asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24,	/* Same as above */
	sizeof(asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24)
		/sizeof(asn_DEF_posSRS_TxFH_WithTimeWindow_r18_tags_24[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_posSRS_TxFH_WithTimeWindow_r18_constr_24,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_posSRS_TxFH_WithTimeWindow_r18_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ext3_13[] = {
	{ ATF_POINTER, 10, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_14,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-Preconfigured-RRC-InactiveInitialUL-BWP-r18"
		},
	{ ATF_POINTER, 9, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-Preconfigured-RRC-InactiveOutsideInitialUL-BWP-r18"
		},
	{ ATF_POINTER, 8, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-ValidityAreaRRC-InactiveInitialUL-BWP-r18"
		},
	{ ATF_POINTER, 7, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_20,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-ValidityAreaRRC-InactiveOutsideInitialUL-BWP-r18"
		},
	{ ATF_POINTER, 6, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_TxFH_RRC_Connected_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_TxFrequencyHoppingRRC_Connected_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-TxFH-RRC-Connected-r18"
		},
	{ ATF_POINTER, 5, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_TxFH_RRC_Inactive_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_TxFrequencyHoppingRRC_Inactive_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-TxFH-RRC-Inactive-r18"
		},
	{ ATF_POINTER, 4, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_TxFH_WithTimeWindow_r18),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_posSRS_TxFH_WithTimeWindow_r18_24,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-TxFH-WithTimeWindow-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_BWA_RRC_Inactive_r18),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_BWA_RRC_Inactive_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-BWA-RRC-Inactive-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_BWA_RRC_Connected_r18),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_BWA_RRC_Connected_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-BWA-RRC-Connected-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct SRS_CapabilityPerBand_r16__ext3, posSRS_BWA_IndependentCA_RRC_Connected_r18),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosSRS_BWA_IndependentCA_RRC_Connected_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"posSRS-BWA-IndependentCA-RRC-Connected-r18"
		},
};
static const int asn_MAP_ext3_oms_13[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_ext3_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext3_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* posSRS-Preconfigured-RRC-InactiveInitialUL-BWP-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* posSRS-Preconfigured-RRC-InactiveOutsideInitialUL-BWP-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* posSRS-ValidityAreaRRC-InactiveInitialUL-BWP-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* posSRS-ValidityAreaRRC-InactiveOutsideInitialUL-BWP-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* posSRS-TxFH-RRC-Connected-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* posSRS-TxFH-RRC-Inactive-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* posSRS-TxFH-WithTimeWindow-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* posSRS-BWA-RRC-Inactive-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* posSRS-BWA-RRC-Connected-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* posSRS-BWA-IndependentCA-RRC-Connected-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext3_specs_13 = {
	sizeof(struct SRS_CapabilityPerBand_r16__ext3),
	offsetof(struct SRS_CapabilityPerBand_r16__ext3, _asn_ctx),
	asn_MAP_ext3_tag2el_13,
	10,	/* Count of tags in the map */
	asn_MAP_ext3_oms_13,	/* Optional members */
	10, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext3_13 = {
	"ext3",
	"ext3",
	&asn_OP_SEQUENCE,
	asn_DEF_ext3_tags_13,
	sizeof(asn_DEF_ext3_tags_13)
		/sizeof(asn_DEF_ext3_tags_13[0]) - 1, /* 1 */
	asn_DEF_ext3_tags_13,	/* Same as above */
	sizeof(asn_DEF_ext3_tags_13)
		/sizeof(asn_DEF_ext3_tags_13[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext3_13,
	10,	/* Elements count */
	&asn_SPC_ext3_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SRS_CapabilityPerBand_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_CapabilityPerBand_r16, freqBandIndicatorNR_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqBandIndicatorNR_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"freqBandIndicatorNR-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct SRS_CapabilityPerBand_r16, olpc_SRS_Pos_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OLPC_SRS_Pos_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"olpc-SRS-Pos-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct SRS_CapabilityPerBand_r16, spatialRelationsSRS_Pos_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpatialRelationsSRS_Pos_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"spatialRelationsSRS-Pos-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct SRS_CapabilityPerBand_r16, ext1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ext1_6,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_POINTER, 2, offsetof(struct SRS_CapabilityPerBand_r16, ext2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ext2_11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext2"
		},
	{ ATF_POINTER, 1, offsetof(struct SRS_CapabilityPerBand_r16, ext3),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_ext3_13,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext3"
		},
};
static const int asn_MAP_SRS_CapabilityPerBand_r16_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_SRS_CapabilityPerBand_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SRS_CapabilityPerBand_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* freqBandIndicatorNR-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* olpc-SRS-Pos-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* spatialRelationsSRS-Pos-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ext2 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* ext3 */
};
asn_SEQUENCE_specifics_t asn_SPC_SRS_CapabilityPerBand_r16_specs_1 = {
	sizeof(struct SRS_CapabilityPerBand_r16),
	offsetof(struct SRS_CapabilityPerBand_r16, _asn_ctx),
	asn_MAP_SRS_CapabilityPerBand_r16_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_SRS_CapabilityPerBand_r16_oms_1,	/* Optional members */
	2, 3,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SRS_CapabilityPerBand_r16 = {
	"SRS-CapabilityPerBand-r16",
	"SRS-CapabilityPerBand-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_SRS_CapabilityPerBand_r16_tags_1,
	sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1)
		/sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1[0]), /* 1 */
	asn_DEF_SRS_CapabilityPerBand_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1)
		/sizeof(asn_DEF_SRS_CapabilityPerBand_r16_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SRS_CapabilityPerBand_r16_1,
	6,	/* Elements count */
	&asn_SPC_SRS_CapabilityPerBand_r16_specs_1	/* Additional specs */
};

