if(HAVE_SPLICE)
    include(CheckSymbolExists)
    list(APPEND CMAKE_REQUIRED_DEFINITIONS -D_GNU_SOURCE)
    check_symbol_exists(splice "fcntl.h;unistd.h" SPLICE_EXISTS)
    if(SPLICE_EXISTS)
        add_definitions(-DHAVE_SPLICE=1)
        message(STATUS "splice() system call is available")
    else()
        message(STATUS "splice() system call is not available")
    endif()
endif()
