if(USE_TIMETRACE)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 19)
            add_compile_options(-ftime-trace)
            message(STATUS "Clang time-trace enabled")
        else()
            message(WARNING "USE_TIMETRACE requires Clang 19 or above, current version is ${CMAKE_CXX_COMPILER_VERSION}")
        endif()
    else()
        message(WARNING "USE_TIMETRACE requires Clang compiler, current compiler is ${CMAKE_CXX_COMPILER_ID}")
    endif()
endif()
