set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

execute_process(COMMAND sh -c "ct-ng show-tuple" OUTPUT_VARIABLE CROSS_TUPLE OUTPUT_STRIP_TRAILING_WHITESPACE)
set(CMAKE_C_COMPILER /root/x-tools/${CROSS_TUPLE}/bin/${CROSS_TUPLE}-gcc)
set(CMAKE_CXX_COMPILER /root/x-tools/${CROSS_TUPLE}/bin/${CROSS_TUPLE}-g++)

set(CMAKE_FIND_ROOT_PATH /root/x-tools/${CROSS_TUPLE})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
