
option(USE_OPENSSL "USE_OPENSSL" OFF)
option(USE_ASAN "USE_ASAN" OFF)
option(ASN_DEBUG "ASN_DEBUG" OFF)

option(INCLUDE_GENERATOR_RTCM "Include RTCM generator" ON)
option(INCLUDE_GENERATOR_SPARTN "Include SPARTN generator" ON)
option(INCLUDE_GENERATOR_SPARTN_OLD "Include old SPARTN generator" OFF)

option(BUILD_WITH_ALL_WARNINGS "BUILD_WITH_ALL_WARNINGS" OFF)
option(WARNINGS_AS_ERRORS "WARNINGS_AS_ERRORS" OFF)

option(BUILD_EXAMPLES "BUILD_EXAMPLES" ON)
