
option(USE_OPENSSL "USE_OPENSSL" OFF)
option(USE_ASAN "USE_ASAN" OFF)
option(ASN_DEBUG "ASN_DEBUG" OFF)

option(INCLUDE_GENERATOR_RTCM "Include RTCM generator" ON)
option(INCLUDE_GENERATOR_SPARTN "Include SPARTN generator" ON)
option(INCLUDE_GENERATOR_TOKORO "Include Tokoro generator" ON)

option(BUILD_WITH_ALL_WARNINGS "BUILD_WITH_ALL_WARNINGS" OFF)
option(WARNINGS_AS_ERRORS "WARNINGS_AS_ERRORS" OFF)

option(BUILD_EXAMPLES "BUILD_EXAMPLES" ON)
option(USE_DWARF4 "USE_DWARF4" OFF)
option(DISABLE_LOGGING "DISABLE_LOGGING" OFF)
option(DATA_TRACING "DATA_TRACING" OFF)
