
option(USE_OPENSSL "USE_OPENSSL" OFF)
option(USE_ASAN "USE_ASAN" OFF)
option(ASN_DEBUG "ASN_DEBUG" OFF)

option(HAVE_SPLICE "Enable splice() system call for zero-copy data transfer" ON)

option(INCLUDE_GENERATOR_RTCM "Include RTCM generator" ON)
option(INCLUDE_GENERATOR_SPARTN "Include SPARTN generator" ON)
option(INCLUDE_GENERATOR_TOKORO "Include Tokoro generator" ON)
option(INCLUDE_GENERATOR_IDOKEIDO "Include idokeido engine" OFF)
option(INCLUDE_FORMAT_RINEX "Include RINEX format support" ON)

option(BUILD_WITH_ALL_WARNINGS "BUILD_WITH_ALL_WARNINGS" OFF)
option(WARNINGS_AS_ERRORS "WARNINGS_AS_ERRORS" OFF)

option(BUILD_EXAMPLES "BUILD_EXAMPLES" ON)
option(USE_DWARF4 "USE_DWARF4" OFF)
option(DISABLE_LOGGING "DISABLE_LOGGING" OFF)
option(DISABLE_TRACE "DISABLE_TRACE" OFF)
option(DISABLE_VERBOSE "DISABLE_TRACE" OFF)
option(DISABLE_DEBUG "DISABLE_DEBUG" OFF)
option(DISABLE_INFO "DISABLE_INFO" OFF)
option(DISABLE_NOTICE "DISABLE_NOTICE" OFF)
option(DISABLE_WARNING "DISABLE_WARNING" OFF)
option(DISABLE_ERROR "DISABLE_ERROR" OFF)
option(LOG_FUNCTION_PERFORMANCE "LOG_FUNCTION_PERFORMANCE" OFF)
option(DATA_TRACING "DATA_TRACING" OFF)
option(DISABLE_STRERRORNAME_NP "DISABLE_STRERRORNAME_NP" OFF)

option(USE_CPM "USE_CPM" OFF)
option(USE_TIMETRACE "USE_TIMETRACE" OFF)
option(UNITY_BUILD "Enable unity build" OFF)
option(SHUFFLE_UNITY_SOURCES "Shuffle source files for unity build" OFF)
option(BUILD_TESTING "BUILD_TESTING" OFF)

